# Generated by Django 6.0.7 on 2026-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starkbank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookInvoiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('gateway_reference_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
