# Generated by Django 6.0.7 on 2026-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starkbank_app", "0003_invoice_gateway_transfer_reference_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="gateway_transfer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
