# Generated by Django 6.0.7 on 2026-07-13 15:08

import starkbank_app.fake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starkbank_app", "0004_invoice_gateway_transfer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="document",
            field=models.CharField(
                max_length=11, validators=[starkbank_app.fake.validate_cpf]
            ),
        ),
    ]
