# Generated by Django 6.0.7 on 2026-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starkbank_app", "0005_alter_customer_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="gateway_transfer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Transfer requested"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("transfer_in_progress", "Transfer in progress"),
                    ("transferred", "Transferred"),
                    ("canceled", "Canceled"),
                    ("refused", "Refused"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
